before_deploy:
  pip install --user awscli
deploy:
  provider: s3
  # You can refer to environment variables from Travis repo settings!
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  # Name of the S3 bucket to which your site should be uploaded.
  bucket: test-techbeach
  # Prevent Travis from deleting your built site so it can be uploaded.
  skip_cleanup: true